# Generated by Django 3.2 on 2021-05-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.IntegerField()),
                ('carName', models.CharField(max_length=30)),
                ('priceDay', models.FloatField()),
                ('priceWeek', models.FloatField()),
                ('numSeats', models.IntegerField()),
                ('numDoors', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('gear', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.IntegerField()),
                ('typeDesc', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.users')),
            ],
        ),
    ]
