# Generated by Django 3.2 on 2021-05-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=30)),
                ('priceDay', models.FloatField()),
                ('priceWeek', models.FloatField()),
                ('numSeats', models.IntegerField()),
                ('numDoors', models.IntegerField()),
                ('gear', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AlterField(
            model_name='booking',
            name='carID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car'),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
