# Generated by Django 3.0.11 on 2021-05-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingID',
        ),
    ]
